AlexEntityRazor/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

AlexEntityRazor/Pages/AddCustomer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class AddCustomerModel : PageModel
    {
        [BindProperty]
        public Customer customer { get; set; }

        DatabaseContext context;


        public AddCustomerModel(DatabaseContext database)
        {
            context = database;
        }

        public void OnGet()
        {

        }


        public ActionResult OnPost()
        {
            var Customer = customer;
            if (!ModelState.IsValid)
            {
                return RedirectToPage("ViewAllCustomer");
            }
            customer.ID = 0;
            var result = context.Add(customer);
            context.SaveChanges();
            return RedirectToPage("ViewAllCustomer");
        }
    }
}

AlexEntityRazor/Pages/AddQuery.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class AddQueryModel : PageModel
    {
        [BindProperty]
        public Contact contact { get; set; }

        DatabaseContext context;


        public AddQueryModel(DatabaseContext database)
        {
            context = database;
        }


        public void OnGet()
        {
        }


        public ActionResult OnPost()
        {
            var Contact = contact;
            if (!ModelState.IsValid)
            {
                return RedirectToPage("ViewAllQuery");
            }
            contact.id = 0;
            var result = context.Add(Contact);
            context.SaveChanges();
            return RedirectToPage("ViewAllQuery");
        }
    }
}

AlexEntityRazor/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

AlexEntityRazor/Pages/EditCustomer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class EditCustomerModel : PageModel
    {
        DatabaseContext Context;
        public EditCustomerModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        [BindProperty]
        public Customer Customer{ get; set; }


        public void OnGet(int? id)
        {
            if (id != null)
            {
                var data = (from Customer in Context.Customer
                            where Customer.ID == id
                            select Customer).SingleOrDefault();

                Customer = data;
            }

        }



        public ActionResult OnPost()
        {
            var customer = Customer;
            if (!ModelState.IsValid)
            {
                return RedirectToPage("ViewAllCustomer");
            }

            Context.Entry(customer).Property(x => x.Name).IsModified = true;
            Context.Entry(customer).Property(x => x.Address).IsModified = true;
            Context.Entry(customer).Property(x => x.Contact).IsModified = true;
            Context.Entry(customer).Property(x => x.Services).IsModified = true;
            Context.Entry(customer).Property(x => x.Charges).IsModified = true;
            Context.SaveChanges();
            return RedirectToPage("ViewAllCustomer");
        }

    }
}

AlexEntityRazor/Pages/EditQuery.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class EditQueryModel : PageModel
    {
        DatabaseContext Context;
        public EditQueryModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        [BindProperty]
        public Contact Contact { get; set; }


        public void OnGet(int? id)
        {
            if (id != null)
            {
                var data = (from Contact in Context.Contact
                            where Contact.id == id
                            select Contact).SingleOrDefault();

                Contact = data;
            }

        }



        public ActionResult OnPost()
        {
            var contact = Contact;
            if (!ModelState.IsValid)
            {
                return RedirectToPage("ViewAllQuery");
            }

            Context.Entry(contact).Property(x => x.Name).IsModified = true;
            Context.Entry(contact).Property(x => x.Email).IsModified = true;
            Context.Entry(contact).Property(x => x.Message).IsModified = true;
            Context.SaveChanges();
            return RedirectToPage("ViewAllQuery");
        }

    }
}

AlexEntityRazor/Pages/EditServices.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class EditServicesModel : PageModel
    {
        DatabaseContext Context;
        public EditServicesModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        [BindProperty]
        public Service service { get; set; }

        public void OnGet(int? id)
        {
            if (id != null)
            {
                var data = (from Service in Context.services
                            where Service.ID == id
                            select Service).SingleOrDefault();

                service = data;
            }
                
        }


        public ActionResult OnPost()
        {
            var Service = service;
            if (!ModelState.IsValid)
            {
                return RedirectToPage("ViewAllServices");
            }

            Context.Entry(Service).Property(x => x.Name).IsModified = true;
            Context.Entry(Service).Property(x => x.Specification).IsModified = true;
            Context.Entry(Service).Property(x => x.Charges).IsModified = true;
            Context.SaveChanges();
            return RedirectToPage("ViewAllServices");
        }

    }
}

AlexEntityRazor/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AlexEntityRazor/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AlexEntityRazor/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AlexEntityRazor/Pages/Services.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class ServicesModel : PageModel
    {
        [BindProperty]

        public Service service { get; set; }
        DatabaseContext context;


        public ServicesModel(DatabaseContext database) {
            context = database;
        }


        public void OnGet()
        {
            
        }
        
        public ActionResult OnPost() {
            var services = service;
            if (!ModelState.IsValid) {
                return RedirectToPage("ViewAllServices");
            }
            service.ID = 0;
            var result = context.Add(services);
            context.SaveChanges();
            return RedirectToPage("ViewAllServices");
        }
    }
}

AlexEntityRazor/Pages/ViewAllCustomer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class ViewAllCustomerModel : PageModel
    {
        DatabaseContext Context;

        public ViewAllCustomerModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        public List<Customer> CustomerList { get; set; }

        public void OnGet()
        {
            var data = (from Customerlist in Context.Customer
                        select Customerlist).ToList();

            CustomerList = data;

        }


        public ActionResult OnGetDelete(int? id)
        {

            if (id != null)
            {
                var data = (from Customer in Context.Customer
                            where Customer.ID == id
                            select Customer).SingleOrDefault();

                Context.Remove(data);
                Context.SaveChanges();
            }
            return RedirectToPage("ViewAllCustomer");
        }

    }
}

AlexEntityRazor/Pages/ViewAllQuery.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class ViewAllQueryModel : PageModel
    {
        DatabaseContext Context;

        public ViewAllQueryModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        public List<Contact> ContactList { get; set; }

        public void OnGet()
        {
            var data = (from Contactlist in Context.Contact
                        select Contactlist).ToList();

            ContactList = data;

        }


        public ActionResult OnGetDelete(int? id)
        {

            if (id != null)
            {
                var data = (from Contact in Context.Contact
                            where Contact.id == id
                            select Contact).SingleOrDefault();

                Context.Remove(data);
                Context.SaveChanges();
            }
            return RedirectToPage("ViewAllQuery");
        }

    }
}

AlexEntityRazor/Pages/ViewAllServices.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlexEntityRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlexEntityRazor.Pages
{
    public class ViewAllServicesModel : PageModel
    {
        DatabaseContext Context;

        public ViewAllServicesModel(DatabaseContext databasecontext)
        {
            Context = databasecontext;
        }

        public List<Service> ServiceList { get; set; }


        public void OnGet()
        {

            var data = (from Servicelist in Context.services
                        select Servicelist).ToList();

            ServiceList = data;
        }


        public ActionResult OnGetDelete(int? id) {

            if (id != null)
            {
                var data = (from Service in Context.services
                            where Service.ID == id
                            select Service).SingleOrDefault();

                Context.Remove(data);
                Context.SaveChanges();
            }
            return RedirectToPage("ViewAllServices");
        }
    }
}

AlexEntityRazor/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

AlexEntityRazor/Pages/AddCustomer.cshtml
@page
@using AlexEntityRazor.Model @*namespace*@
@model AddCustomerModel


<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


<div class="container">
    <h3>Add Customer</h3>
    <hr />
    <br />
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="customer.Name"></label>
                <input asp-for="customer.Name" class="form-control" />
                <span class="alert-danger" asp-validation-for="customer.Name"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="customer.Address"></label>
                <input asp-for="customer.Address" class="form-control" />
                <span class="alert-danger" asp-validation-for="customer.Address"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="customer.Contact"></label>
                <input asp-for="customer.Contact" class="form-control" />
                <span class="alert-danger" asp-validation-for="customer.Contact"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="customer.Services"></label>
                <input asp-for="customer.Services" class="form-control" />
                <span class="alert-danger" asp-validation-for="customer.Services"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="customer.Charges"></label>
                <input asp-for="customer.Charges" class="form-control" />
                <span class="alert-danger" asp-validation-for="customer.Charges"></span>
            </div>
        </div>



        <br />
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-default" href="/ViewAllCustomer">Cancel</a>
    </form>
</div>

AlexEntityRazor/Pages/AddQuery.cshtml
@page
@using AlexEntityRazor.Model @*namespace*@
@model AddQueryModel



<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


<div class="container">
    <h3>Add Query</h3>
    <hr />
    <br />
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="contact.Name"></label>
                <input asp-for="contact.Name" class="form-control" />
                <span class="alert-danger" asp-validation-for="contact.Name"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="contact.Email"></label>
                <input asp-for="contact.Email" class="form-control" />
                <span class="alert-danger" asp-validation-for="contact.Email"></span>
            </div>
        </div>
       

        <div class="row">
            <div class="col-md-4">
                <label asp-for="contact.Message"></label>
                <input asp-for="contact.Message" class="form-control" />
                <span class="alert-danger" asp-validation-for="contact.Message"></span>
            </div>
        </div>



        <br />
        <input type="submit" value="Save Query" class="btn btn-primary" />
        <a class="btn btn-default" href="/ViewAllQuery">Cancel</a>
    </form>
</div>

AlexEntityRazor/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AlexEntityRazor/Pages/EditCustomer.cshtml
@page "{id:int}"
@using AlexEntityRazor.Model

@model EditCustomerModel


<div class="container">
    <h3>Edit Customer</h3>
    <hr />
    <br />
    <form method="post">
        <input asp-for="Customer.ID" type="hidden" />
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Customer.Name"></label>
                <input asp-for="Customer.Name" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Customer.Address"></label>
                <input asp-for="Customer.Address" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Customer.Contact"></label>
                <input asp-for="Customer.Contact" class="form-control" />
            </div>
        </div>


        <div class="row">
            <div class="col-md-4">
                <label asp-for="Customer.Services"></label>
                <input asp-for="Customer.Services" class="form-control" />
            </div>
        </div>


        <div class="row">
            <div class="col-md-4">
                <label asp-for="Customer.Charges"></label>
                <input asp-for="Customer.Charges" class="form-control" />
            </div>
        </div>

        <br />
        <input type="submit" value="Update" class="btn btn-primary" />
        <a class="btn btn-default" href="/ViewAllCustomer">Cancel</a>
    </form>
</div>

AlexEntityRazor/Pages/EditQuery.cshtml
@page "{id:int}"
@using AlexEntityRazor.Model

@model EditQueryModel


<div class="container">
    <h3>Edit Query</h3>
    <hr />
    <br />
    <form method="post">
        <input asp-for="Contact.id" type="hidden" />
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Contact.Name"></label>
                <input asp-for="Contact.Name" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Contact.Email"></label>
                <input asp-for="Contact.Email" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Contact.Message"></label>
                <input asp-for="Contact.Message" class="form-control" />
            </div>
        </div>
        <br />
        <input type="submit" value="Update" class="btn btn-primary" />
        <a class="btn btn-default" href="/ViewAllQuery">Cancel</a>
    </form>
</div>

AlexEntityRazor/Pages/EditServices.cshtml
@page "{id:int}"
@using AlexEntityRazor.Model
@model EditServicesModel

<div class="container">
    <h3>Edit Services</h3>
    <hr />
    <br />
    <form method="post">
        <input asp-for="service.ID" type="hidden" />
        <div class="row">
            <div class="col-md-4">
                <label asp-for="service.Name"></label>
                <input asp-for="service.Name" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="service.Specification"></label>
                <input asp-for="service.Specification" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="service.Charges"></label>
                <input asp-for="service.Charges" class="form-control" />
            </div>
        </div>

        <br />
        <input type="submit" value="Update" class="btn btn-primary" />
        <a class="btn btn-default" href="/ViewAllServices">Cancel</a>
    </form>
</div>

AlexEntityRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

AlexEntityRazor/Pages/ViewAllCustomer.cshtml
@page
@using AlexEntityRazor.Model

@model ViewAllCustomerModel


<h2>View All Customer</h2>



<p>
    <a asp-page="AddCustomer">Add New Customer</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Address")
            </th>

            <th>
                @Html.DisplayName("Contact")
            </th>


            <th>
                @Html.DisplayName("Services")
            </th>
            <th>
                @Html.DisplayName("Charges")
            </th>
            <th>Edit | Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CustomerList)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Services)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Charges)
            </td>
            <td>
                <a asp-page="./EditCustomer" asp-route-id="@item.ID">Edit</a> |
                <a asp-page="./ViewAllCustomer" onclick="return confirm('Are you sure you want to delete this item?');" asp-page-handler="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table> 

AlexEntityRazor/Pages/ViewAllQuery.cshtml
@page
@using AlexEntityRazor.Model

@model ViewAllQueryModel



<h2>View All Queries</h2>



<p>
    <a asp-page="AddQuery">Add New Query</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Email")
            </th>

            <th>
                @Html.DisplayName("Message")
            </th>


            <th>Edit | Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ContactList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
              
                <td>
                    <a asp-page="./EditQuery" asp-route-id="@item.id">Edit</a> |
                    <a asp-page="./ViewAllQuery" onclick="return confirm('Are you sure you want to delete this item?');" asp-page-handler="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table> 

AlexEntityRazor/Pages/ViewAllServices.cshtml
@page
@using AlexEntityRazor.Model
@model ViewAllServicesModel


<h2>View All Services</h2>



<p>
    <a asp-page="Services">Add New Service</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Specification")
            </th>
            <th>
                @Html.DisplayName("Charges")
            </th>
            <th>Edit | Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ServiceList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Specification)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Charges)
                </td>
               <td>
                    <a asp-page="./EditServices" asp-route-id="@item.ID">Edit</a> |
                    <a asp-page="./ViewAllServices" onclick="return confirm('Are you sure you want to delete this item?');" asp-page-handler="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table> 